services:
  # 1. PHP Service (Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trip_builder_app
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - trip-builder-network

  # 2. Nginx Service (Web Server)
  web:
    image: nginx:stable-alpine
    container_name: trip_builder_web
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - trip-builder-network

  # 3. MySQL Service (Database)
  db:
    image: mysql:8.0
    container_name: trip_builder_db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - trip-builder-network

volumes:
  dbdata:
    driver: local

networks:
  trip-builder-network:
    driver: bridge
